apiVersion: v1
kind: Secret
metadata:
  name: team-retrospective-secrets
  labels:
    app: team-retrospective
    app.kubernetes.io/name: team-retrospective
    app.kubernetes.io/component: secrets
stringData:
  POSTGRES_DB: retrogemini
  POSTGRES_USER: retrogemini
  POSTGRES_PASSWORD: change-me
  SUPER_ADMIN_PASSWORD: change-me
